workflow:
  dataset_creation: Yes
  dnn_training: Yes
  dnn_evaluation: Yes
# ---------------------------------
dataset_creation_settings: !include dataset_creation.yaml
# -----------------------------------
feature_extraction_settings: !include feature_extraction.yaml
# -----------------------------------
dnn_training_settings: !include method_cwr-wl.yaml
# -----------------------------------
dirs_and_files: !include dirs_and_files_cwr-wl.yaml
# EOF
